//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace juip.app.Controllers {
    
    
    public partial class Application {
        
        /// <summary>
        /// Controller control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::juip.app.Controllers.ApplicationController Controller;
        
        /// <summary>
        /// HomeView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::juip.app.Views.Home HomeView;
        
        /// <summary>
        /// StudentBrowseView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::juip.app.Views.StudentBrowseView StudentBrowseView;
        
        /// <summary>
        /// StudentProfileAddView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::juip.app.Views.StudentProfileAddView StudentProfileAddView;
        
        /// <summary>
        /// StudentProfileEditView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::juip.app.Views.StudentProfileEditView StudentProfileEditView;
        
        /// <summary>
        /// StudentProfileView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::juip.app.Views.StudentProfileView StudentProfileView;
    }
}
